project_id = "dhbvweazpqnviqwgpurv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[functions.search-cities]
verify_jwt = false

[functions.search-travel-options]
verify_jwt = false