project_id = "dhbvweazpqnviqwgpurv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[functions.get-mapbox-token]
verify_jwt = false

[functions.search-cities]
verify_jwt = false

[functions.search-travel-options]
verify_jwt = false

[functions.search-yelp-businesses]
verify_jwt = false

[functions.enhance-city-formatting]
verify_jwt = false

[functions.manage-user-roles]
verify_jwt = true

[functions.booking-com-api]
verify_jwt = true

[functions.get-stripe-prices]
verify_jwt = false

[functions.amadeus-activities]
verify_jwt = true

[functions.amadeus-flights]
verify_jwt = true

[functions.categorize-search-results]
verify_jwt = false

[functions.chat-with-gpt]
verify_jwt = true

[functions.get-payment-info]
verify_jwt = false

[functions.generate-reminders]
verify_jwt = false

[functions.track-booking-event]
verify_jwt = false

[functions.create-booking-checkout]
verify_jwt = false

[functions.booking-webhook]
verify_jwt = false
