// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-places.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
var search_places_default = defineTool({
  name: "search_places",
  title: "Search places",
  description: "Search for cities, regions, and countries by name using TAAI Travel's place search. Returns up to 8 matches with place name, region/country context, and coordinates.",
  inputSchema: {
    query: z.string().min(2).describe("Place name to search (city, region, or country). Minimum 2 characters.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    const supabaseUrl2 = process.env.SUPABASE_URL;
    if (!supabaseUrl2) {
      return {
        content: [{ type: "text", text: "Server not configured (SUPABASE_URL missing)." }],
        isError: true
      };
    }
    const res = await fetch(`${supabaseUrl2}/functions/v1/search-cities`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query })
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return {
        content: [{ type: "text", text: `Place search failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    const data = await res.json();
    const features = Array.isArray(data?.features) ? data.features : [];
    const results = features.slice(0, 8).map((f) => ({
      name: f?.place_name ?? f?.text ?? "",
      short_name: f?.text ?? "",
      place_type: Array.isArray(f?.place_type) ? f.place_type[0] : void 0,
      longitude: Array.isArray(f?.center) ? f.center[0] : void 0,
      latitude: Array.isArray(f?.center) ? f.center[1] : void 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/about-taai.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var ABOUT = {
  name: "TAAI Travel",
  tagline: "AI-powered travel planning and booking",
  description: "TAAI Travel is a premium travel-planning platform that combines an AI concierge with real-time hotel, flight, and activity search. Users create itineraries, collaborate with travel companions, capture and book options, and manage trips end-to-end.",
  website: "https://taai-test.lovable.app",
  capabilities: [
    "Search hotels, flights, and activities across multiple providers",
    "AI-generated itineraries with day-by-day planning",
    "Shared itineraries and collaborative trip planning",
    "Integrated checkout and booking"
  ]
};
var about_taai_default = defineTool2({
  name: "about_taai",
  title: "About TAAI Travel",
  description: "Return a short description of TAAI Travel, its capabilities, and website. Useful when an assistant is first connected and wants to know what this MCP server can do.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ABOUT, null, 2) }],
    structuredContent: ABOUT
  })
});

// src/lib/mcp/index.ts
var supabaseUrl = (process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || "https://dhbvweazpqnviqwgpurv.supabase.co").replace(/\/+$/, "");
var mcp_default = defineMcp({
  name: "taai-travel-mcp",
  title: "TAAI Travel",
  version: "0.1.0",
  instructions: "Tools for TAAI Travel. Use `about_taai` to learn what the platform does. Use `search_places` to resolve a city, region, or country name to coordinates before planning a trip.",
  auth: auth.oauth.issuer({
    issuer: `${supabaseUrl}/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_places_default, about_taai_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
