// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxlyiptrvfbtglueijkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bHlpcHRydmZidGdsdWVpamtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTcyNjQsImV4cCI6MjA2NzE3MzI2NH0.6ZH80EarJBiQ2ioi7c_CZ78iI-tco1NgqLE2Wk4WQPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});